INSERT INTO `Content` (`id`, `type`, `url`, `section`, `sitemap`) VALUES
(1, 'Home Page', '', 'general', 0),
(2, 'Home Page Bottom', '', 'general', 0),
(3, 'Directory Results', '', 'general', 0),
(4, 'Directory Results Bottom', '', 'general', 0),
(5, 'Advertise with Us', '', 'advertise_general', 0),
(6, 'Advertise with Us Bottom', '', 'advertise_general', 0),
(9, 'Contact Us', '', 'general', 0),
(10, 'Terms of Use', '', 'general', 0),
(11, 'Listing Advertisement', '', 'advertise_listing', 0),
(12, 'Listing Home', '', 'listing', 0),
(13, 'Listing Home Bottom', '', 'listing',0),
(14, 'Listing Results', '', 'listing', 0),
(15, 'Listing Results Bottom', '', 'listing', 0),
(16, 'Listing View All Categories', '', 'listing', 0),
(17, 'Listing View All Categories Bottom', '', 'listing', 0),
(18, 'Deal Home', '', 'listing', 0),
(19, 'Deal Home Bottom',  '', 'listing', 0),
(20, 'Deal Results', '', 'listing', 0),
(21, 'Deal Results Bottom', '', 'listing', 0),
(22, 'Deal View All Categories', '', 'listing', 0),
(23, 'Deal View All Categories Bottom', '', 'listing', 0),
(24, 'Event Advertisement', '', 'advertise_event', 0),
(25, 'Event Home', '', 'event', 0),
(26, 'Event Home Bottom', '', 'event', 0),
(27, 'Event Results', '', 'event', 0),
(28, 'Event Results Bottom', '', 'event', 0),
(29, 'Event View All Categories', '', 'event', 0),
(30, 'Event View All Categories Bottom', '', 'event', 0),
(31, 'Banner Advertisement', '', 'advertise_banner', 0),
(32, 'Classified Advertisement', '', 'advertise_classified', 0),
(33, 'Classified Home', '', 'classified', 0),
(34, 'Classified Home Bottom', '', 'classified', 0),
(35, 'Classified Results', '', 'classified', 0),
(36, 'Classified Results Bottom', '', 'classified', 0),
(37, 'Classified View All Categories', '', 'classified', 0),
(38, 'Classified View All Categories Bottom', '', 'classified', 0),
(39, 'Article Advertisement', '', 'advertise_article', 0),
(40, 'Article Home', '', 'article', 0),
(41, 'Article Home Bottom', '', 'article', 0),
(42, 'Article Results', '', 'article', 0),
(43, 'Article Results Bottom', '', 'article', 0),
(44, 'Article View All Categories', '', 'article', 0),
(45, 'Article View All Categories Bottom', '', 'article', 0),
(46, 'Sponsor Home', '', 'member', 0),
(47, 'Sponsor Home Bottom', '', 'member', 0),
(48, 'Manage Account', '', 'member', 0),
(49, 'Manage Account Bottom', '', 'member', 0),
(50, 'Sponsor Help', '', 'member', 0),
(51, 'Sponsor Help Bottom', '', 'member', 0),
(52, 'Manage Listings', '', 'member', 0),
(53, 'Manage Listings Bottom', '', 'member', 0),
(56, 'Manage Deals', '', 'member', 0),
(57, 'Manage Deals Bottom', '', 'member', 0),
(58, 'Manage Events', '', 'member', 0),
(59, 'Manage Events Bottom', '', 'member', 0),
(60, 'Manage Banners', '', 'member', 0),
(61, 'Manage Banners Bottom', '', 'member', 0),
(62, 'Manage Classifieds', '', 'member', 0),
(63, 'Manage Classifieds Bottom', '', 'member', 0),
(64, 'Manage Articles', '', 'member', 0),
(65, 'Manage Articles Bottom', '', 'member', 0),
(66, 'Transaction', '', 'member', 0),
(67, 'Transaction Bottom', '', 'member', 0),
(68, 'Sitemap', '', 'general', 0),
(69, 'Error Page', '', 'general', 0),
(71, 'Maintenance Page', '', 'general', 0),
(72, 'Profile Page', '', 'general', 0),
(73, 'Profile Page Bottom', '', 'general', 0),
(74, 'Add Profile Page', '', 'general', 0),
(75, 'Packages Offer', '', 'advertise_general', 0);