INSERT INTO `CustomText_Lang` (`name`, `lang`, `value`) VALUES
('claim_textlink', 'en_us', 'Is this your listing?'),
('claim_textlink', 'pt_br', 'Esta empresa é sua?'),
('claim_textlink', 'es_es', '¿Es éste su anuncio?'),
('claim_textlink', 'fr_fr', 'Est-ce votre liste?'),
('claim_textlink', 'it_it', 'È questo il tuo listing?'),
('claim_textlink', 'ge_ge', 'Ist dies Ihr Einträge?'),
('claim_textlink', 'tr_tr', 'Bu şirket mi?'),
('payment_tax_label', 'en_us', 'Sales Tax'),
('payment_tax_label', 'pt_br', 'Sales Tax'),
('payment_tax_label', 'es_es', 'Sales Tax'),
('payment_tax_label', 'fr_fr', 'Sales Tax'),
('payment_tax_label', 'it_it', 'Sales Tax'),
('payment_tax_label', 'ge_ge', 'Sales Tax'),
('payment_tax_label', 'tr_tr', 'Satış Vergisi'),
('promotion_default_conditions', 'en_us', 'There is a limit of 1 deal per person. The promotional value of this deal expires in 3 months. Deal must be presented in order to receive discount. This deal is not valid for cash back, can only be used once, does not cover tax or gratuities. This deal can not be combined with other offers.'),
('promotion_default_conditions', 'pt_br', 'Limite de uma oferta por pessoa. O valor promocional expira em 3 meses. O cupom deve ser apresentado para receber o desconto. Não é válido para devolução de dinheiro. Pode ser usado uma única vez. Não cobre impostos ou descontos. Não pode ser combinado com outras ofertas.'),
('promotion_default_conditions', 'es_es', 'Límite de un acuerdo por persona. Valor de publicidad expira en 3 meses. Acuerdo debe ser presentado para recibir el descuento. No es válido para dinero en efectivo. Se debe utilizar en una sola visita. No cubre los impuestos o propina. No se puede combinar con otras ofertas.'),
('promotion_default_conditions', 'fr_fr', 'Limite de deal 1 par personne. Valeur publicitaire expire en 3 mois. Deal doit être présentée pour obtenir le rabais. Non valable pour une remise en argent. Vous devez utiliser en une seule visite. Ne couvre pas les taxes ni le service. Ne peut être combiné avec d''autres offres.'),
('promotion_default_conditions', 'it_it', 'Limite di 1 affare a persona. Valore pomotinal scade in 3 mesi. Deal devono essere presentati per ricevere sconti. Non valida per il cash back. Deve usare in una sola visita. Non copre fiscale o gratuità. Non è cumulabile con altre offerte.'),
('promotion_default_conditions', 'ge_ge', 'Limit von 1 Deal pro Person. Die Anpreisungen Wert verfällt nach 3 Monaten. Deal muss vorgelegt Nachlass erhalten. Nicht gültig für Bargeld zurück. Muss bei einem Besuch zu nutzen. Erstreckt sich nicht auf Steuer-oder Trinkgeld. Kann nicht mit anderen Angeboten kombiniert werden.'),
('promotion_default_conditions', 'tr_tr', 'Kişi başına 1 teklif limiti. Teklif değeri 3 ay içinde dolacaktır. İndirimi almak için teklif kuponu gösterilmelidir. Değil karşılığında para almak için kabul etti. Tek ziyarette kullanılmalıdır. Vergi veya bahşişi kapsamaz. Diğer tekliflerle birleştirilemez.');