INSERT INTO `Email_Notification` (`id`, `email`, `days`, `deactivate`, `bcc`, `about`, `content_type`) VALUES
(1, '30 day renewal reminder', 30, '0', '', 'Automatic email sent 30 days before account expiration date to remind listing owners to renew their account.', 'text/plain'),
(2, '15 day renewal reminder', 15, '0', '', 'Automatic email sent 15 days before account expiration date to remind listing owners to renew their account.', 'text/plain'),
(3, '7 day renewal reminder', 7, '0', '', 'Automatic email sent 7 days before account expiration date to remind listing owners to renew their account.', 'text/plain'),
(4, '1 day renewal reminder', 1, '0', '', 'Automatic email sent 1 day before account expiration date to remind listing owners to renew their account.', 'text/plain'),
(5, 'Sponsor Account Create (sitemgr area)', 0, '0', '', 'Email sent to the listing owner when site manager creates an account for him.', 'text/plain'),
(6, 'Sponsor Account Update (sitemgr area)', 0, '0', '', 'Email sent to the listing owner when sitemgr modifies his account in the system.', 'text/plain'),
(7, 'Visitor Account Create (sitemgr area)', 0, '0', '', 'Email sent to the visitor when site manager creates an account for him.', 'text/plain'),
(8, 'Visitor Account Update (sitemgr area)', 0, '0', '', 'Email sent to the visitor when sitemgr modifies his account in the system.', 'text/plain'),
(9, 'Forgotten Password', 0, '0', '', 'Email sent to the listing owner informing his new password when requested.', 'text/plain'),
(10, 'New Listing', 0, '0', '', 'Email sent to the listing owner when he creates a new listing in the directory.', 'text/plain'),
(11, 'New Event', 0, '0', '', 'Email sent to the listing owner when he creates a new event in the directory.', 'text/plain'),
(12, 'New Banner', 0, '0', '', 'Email sent to the banner owner when he creates a new banner in the directory.', 'text/plain'),
(13, 'New Classified', 0, '0', '', 'Email sent to the classified owner when he creates a new classified in the directory.', 'text/plain'),
(14, 'New Article', 0, '0', '', 'Email sent to the article owner when he creates a new article in the directory.', 'text/plain'),
(15, 'Custom Invoice', 0, '0', '', 'Custom Invoice email', 'text/plain'),
(16, 'Active Listing', 0, '0', '', 'Email sent to the listing owner when sitemgr activate the listing.', 'text/plain'),
(17, 'Active Event', 0, '0', '', 'Email sent to the event owner when sitemgr activate the event.', 'text/plain'),
(18, 'Active Banner', 0, '0', '', 'Email sent to the banner owner when sitemgr activate the banner.', 'text/plain'),
(19, 'Active Classified', 0, '0', '', 'Email sent to the classified owner when sitemgr activate the classified.', 'text/plain'),
(20, 'Active Article', 0, '0', '', 'Email sent to the article owner when sitemgr activate the article.', 'text/plain'),
(21, 'Email to Friend', 0, '0', '', 'Email sent from an user to your friend.', 'text/plain'),
(22, 'Listing Signup', 0, '0', '', 'Email sent to the listing owner when he makes the signup process.', 'text/plain'),
(23, 'Event Signup', 0, '0', '', 'Email sent to the event owner when he makes the signup process.', 'text/plain'),
(24, 'Banner Signup', 0, '0', '', 'Email sent to the banner owner when he makes the signup process.', 'text/plain'),
(25, 'Classified Signup', 0, '0', '', 'Email sent to the classified owner when he makes the signup process.', 'text/plain'),
(26, 'Article Signup', 0, '0', '', 'Email sent to the article owner when he makes the signup process.', 'text/plain'),
(27, 'Claimer Signup', 0, '0', '', 'Email sent to the claimer when he makes the signup process.', 'text/plain'),
(28, 'Claim Automatically Approved', 0, '0', '', 'Email sent to the claimer when his claim is approved automatically.', 'text/plain'),
(29, 'Claim Approved', 0, '0', '', 'Email sent to the claimer when his claim is approved.', 'text/plain'),
(30, 'Claim Denied', 0, '0', '', 'Email sent to the claimer when his claim is denied.', 'text/plain'),
(31, 'Approve Reply', 0, '0', '', 'Email sent to the item owner when sitemgr approve the reply.', 'text/plain'),
(32, 'Approve Review', 0, '0', '', 'Email sent to the item owner when sitemgr approve the review.', 'text/plain'),
(33, 'New Review', 0, '0', '', 'Email sent to the item owner when his item receives a new review.', 'text/plain'),
(34, 'Invoice Notification', 0, '0', '', 'Email sent to member when he pays a new item by invoice.', 'text/plain'),
(35, 'Visitor Account Create', 0, '0', '', 'Email sent to the user when he creates a new profile.', 'text/plain'),
(36, 'Sponsor Stats & Engagement E-mail', 0, '0', '', 'Monthly e-mail sent to listing owners that includes their stats and reviews.', 'text/plain');