<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Latitude,Listing Longitude,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Reflections Unlimited & Reneu Day Spa,3035 Monroe Ave,,United States,New York,Rochester,14618,(585) 248-8790,,,,,,Reflections Unlimited & Reneu Day Spa,,,3035 Monroe Ave,,United States,USA,,,Rochester,NY,Rochester,,,,14618,,,(585) 248-8790,,Beauty Salons and Barbers,\"Beauty Salons and Barbers - Rochester, Salon, Barber, Hair, Stylist, Local\",Salon||Barber||Hair||Stylist||Massage,,7/1/2012,active,bronze,Beauty Salons and Barbers,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Attitudes Hair Design,1946 W Ridge Rd,,United States,New York,Rochester,14626,(585) 720-1840,,,,,,Attitudes Hair Design,,,1946 W Ridge Rd,,United States,USA,,,Rochester,NY,Rochester,,,,14626,,,(585) 720-1840,,Beauty Salons and Barbers,\"Beauty Salons and Barbers - Rochester, Salon, Barber, Hair, Stylist, Local\",Salon||Barber||Hair||Stylist||Massage,,7/1/2012,active,bronze,Beauty Salons and Barbers,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Hair Extraordinaire,659 Titus Ave,,United States,New York,Rochester,14617,(585) 266-3433,,,,,,Hair Extraordinaire,,,659 Titus Ave,,United States,USA,,,Rochester,NY,Rochester,,,,14617,,,(585) 266-3433,,Beauty Salons and Barbers,\"Beauty Salons and Barbers - Rochester, Salon, Barber, Hair, Stylist, Local\",Salon||Barber||Hair||Stylist||Massage,,7/1/2012,active,bronze,Beauty Salons and Barbers,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Brow Biz,2450 W Ridge Rd 206,,United States,New York,Rochester,14626,(585) 730-8076,,,,,,Brow Biz,,,2450 W Ridge Rd 206,,United States,USA,,,Rochester,NY,Rochester,,,,14626,,,(585) 730-8076,,Beauty Salons and Barbers,\"Beauty Salons and Barbers - Rochester, Salon, Barber, Hair, Stylist, Local\",Salon||Barber||Hair||Stylist||Massage,,7/1/2012,active,bronze,Beauty Salons and Barbers,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Styles Studio Salon,928 Clinton Ave S,,United States,New York,Rochester,14620,(585) 473-8340,,,,,,Styles Studio Salon,,,928 Clinton Ave S,,United States,USA,,,Rochester,NY,Rochester,,,,14620,,,(585) 473-8340,,Beauty Salons and Barbers,\"Beauty Salons and Barbers - Rochester, Salon, Barber, Hair, Stylist, Local\",Salon||Barber||Hair||Stylist||Massage,,7/1/2012,active,bronze,Beauty Salons and Barbers,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Geometrics Hair Design,1777 English Rd,,United States,New York,Rochester,14616,(585) 723-0720,,,,,,Geometrics Hair Design,,,1777 English Rd,,United States,USA,,,Rochester,NY,Rochester,,,,14616,,,(585) 723-0720,,Beauty Salons and Barbers,\"Beauty Salons and Barbers - Rochester, Salon, Barber, Hair, Stylist, Local\",Salon||Barber||Hair||Stylist||Massage,,7/1/2012,active,bronze,Beauty Salons and Barbers,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Pharaoh's Hairum,4112 W Henrietta Rd,,United States,New York,Rochester,14623,(855) 318-9282,,,,,,Pharaoh's Hairum,,,4112 W Henrietta Rd,,United States,USA,,,Rochester,NY,Rochester,,,,14623,,,(855) 318-9282,,Beauty Salons and Barbers,\"Beauty Salons and Barbers - Rochester, Salon, Barber, Hair, Stylist, Local\",Salon||Barber||Hair||Stylist||Massage,,7/1/2012,active,bronze,Beauty Salons and Barbers,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Maxim Spa & Salon Inc,633 Park Ave,,United States,New York,Rochester,14607,(585) 256-0838,,,,,,Maxim Spa & Salon Inc,,,633 Park Ave,,United States,USA,,,Rochester,NY,Rochester,,,,14607,,,(585) 256-0838,,Beauty Salons and Barbers,\"Beauty Salons and Barbers - Rochester, Salon, Barber, Hair, Stylist, Local\",Salon||Barber||Hair||Stylist||Massage,,7/1/2012,active,bronze,Beauty Salons and Barbers,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Textures Hair Designs,775 Howard Rd,,United States,New York,Rochester,14624,(585) 426-2422,,,,,,Textures Hair Designs,,,775 Howard Rd,,United States,USA,,,Rochester,NY,Rochester,,,,14624,,,(585) 426-2422,,Beauty Salons and Barbers,\"Beauty Salons and Barbers - Rochester, Salon, Barber, Hair, Stylist, Local\",Salon||Barber||Hair||Stylist||Massage,,7/1/2012,active,bronze,Beauty Salons and Barbers,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Studio Expo Hair Inc,2860 Buffalo Rd,,United States,New York,Rochester,14624,(585) 247-2810,,,,,,Studio Expo Hair Inc,,,2860 Buffalo Rd,,United States,USA,,,Rochester,NY,Rochester,,,,14624,,,(585) 247-2810,,Beauty Salons and Barbers,\"Beauty Salons and Barbers - Rochester, Salon, Barber, Hair, Stylist, Local\",Salon||Barber||Hair||Stylist||Massage,,7/1/2012,active,bronze,Beauty Salons and Barbers,,,,,\n";
?>
