<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Latitude,Listing Longitude,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Roberts Communications Inc,64 Commercial St,,United States,New York,Rochester,14614,(585) 325-6000,,,,,,Roberts Communications Inc,,,,,,,,,New York,NY,Rochester,,,,14614,,,(585) 325-6000,,Advertising & Marketing Agencies,\"Advertising & Marketing Agencies - Promotions, Business Development, Public Relations, TV, Radio, Branding, Print, Internet, SEO, SEM, Digital, PPC, Direct Mail, Sales\",\"SEO, SEM, Ads, Marketing, PPC, Branding, Promotions\",,6/29/2012,active,bronze,Advertising & Marketing,Professional Services,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Nagel & Summers Inc,550 Colebrook Dr,,United States,New York,Rochester,14617,(585) 454-4540,,,,,,Nagel & Summers Inc,,,,,,,,,New York,NY,Rochester,,,,14617,,,(585) 454-4540,,Advertising & Marketing Agencies,\"Advertising & Marketing Agencies - Promotions, Business Development, Public Relations, TV, Radio, Branding, Print, Internet, SEO, SEM, Digital, PPC, Direct Mail, Sales\",\"SEO, SEM, Ads, Marketing, PPC, Branding, Promotions\",,6/29/2012,active,bronze,Advertising & Marketing,Professional Services,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Adventures In Advertising,2501 Browncroft Blvd,,United States,New York,Rochester,14625,(585) 248-9250,,,,,,Adventures In Advertising,,,,,,,,,New York,NY,Rochester,,,,14625,,,(585) 248-9250,,Advertising & Marketing Agencies,\"Advertising & Marketing Agencies - Promotions, Business Development, Public Relations, TV, Radio, Branding, Print, Internet, SEO, SEM, Digital, PPC, Direct Mail, Sales\",\"SEO, SEM, Ads, Marketing, PPC, Branding, Promotions\",,6/29/2012,active,bronze,Advertising & Marketing,Professional Services,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Antithesis Advertising,72 Cascade Dr,,United States,New York,Rochester,14614,(585) 232-7740,,,,,,Antithesis Advertising,,,,,,,,,New York,NY,Rochester,,,,14614,,,(585) 232-7740,,Advertising & Marketing Agencies,\"Advertising & Marketing Agencies - Promotions, Business Development, Public Relations, TV, Radio, Branding, Print, Internet, SEO, SEM, Digital, PPC, Direct Mail, Sales\",\"SEO, SEM, Ads, Marketing, PPC, Branding, Promotions\",,6/29/2012,active,bronze,Advertising & Marketing,Professional Services,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Frontline Advertising,890 Westfall Rd Ste C,,United States,New York,Rochester,14618,(585) 244-1300,,,,,,Frontline Advertising,,,,,,,,,New York,NY,Rochester,,,,14618,,,(585) 244-1300,,Advertising & Marketing Agencies,\"Advertising & Marketing Agencies - Promotions, Business Development, Public Relations, TV, Radio, Branding, Print, Internet, SEO, SEM, Digital, PPC, Direct Mail, Sales\",\"SEO, SEM, Ads, Marketing, PPC, Branding, Promotions\",,6/29/2012,active,bronze,Advertising & Marketing,Professional Services,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Jay Advertising Inc,170 Linden Oaks # A,,United States,New York,Rochester,14625,(585) 264-3600,,,,,,Jay Advertising Inc,,,,,,,,,New York,NY,Rochester,,,,14625,,,(585) 264-3600,,Advertising & Marketing Agencies,\"Advertising & Marketing Agencies - Promotions, Business Development, Public Relations, TV, Radio, Branding, Print, Internet, SEO, SEM, Digital, PPC, Direct Mail, Sales\",\"SEO, SEM, Ads, Marketing, PPC, Branding, Promotions\",,6/29/2012,active,bronze,Advertising & Marketing,Professional Services,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Partners Plus Napier,192 Mill St Ste 600,,United States,New York,Rochester,14614,(585) 454-1010,,,,,,Partners Plus Napier,,,,,,,,,New York,NY,Rochester,,,,14614,,,(585) 454-1010,,Advertising & Marketing Agencies,\"Advertising & Marketing Agencies - Promotions, Business Development, Public Relations, TV, Radio, Branding, Print, Internet, SEO, SEM, Digital, PPC, Direct Mail, Sales\",\"SEO, SEM, Ads, Marketing, PPC, Branding, Promotions\",,6/29/2012,active,bronze,Advertising & Marketing,Professional Services,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Archer Communications Inc,252 Alexander St,,United States,New York,Rochester,14607,(585) 461-1570,,,,,,Archer Communications Inc,,,,,,,,,New York,NY,Rochester,,,,14607,,,(585) 461-1570,,Advertising & Marketing Agencies,\"Advertising & Marketing Agencies - Promotions, Business Development, Public Relations, TV, Radio, Branding, Print, Internet, SEO, SEM, Digital, PPC, Direct Mail, Sales\",\"SEO, SEM, Ads, Marketing, PPC, Branding, Promotions\",,6/29/2012,active,bronze,Advertising & Marketing,Professional Services,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Berry Co,155 Corporate Woods,,United States,New York,Rochester,14623,(585) 272-2900,,,,,,Berry Co,,,,,,,,,New York,NY,Rochester,,,,14623,,,(585) 272-2900,,Advertising & Marketing Agencies,\"Advertising & Marketing Agencies - Promotions, Business Development, Public Relations, TV, Radio, Branding, Print, Internet, SEO, SEM, Digital, PPC, Direct Mail, Sales\",\"SEO, SEM, Ads, Marketing, PPC, Branding, Promotions\",,6/29/2012,active,bronze,Advertising & Marketing,Professional Services,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,DAC Group,1600 Chase Sq,,United States,New York,Rochester,14604,(585) 546-6480,,,,,,DAC Group,,,,,,,,,New York,NY,Rochester,,,,14604,,,(585) 546-6480,,Advertising & Marketing Agencies,\"Advertising & Marketing Agencies - Promotions, Business Development, Public Relations, TV, Radio, Branding, Print, Internet, SEO, SEM, Digital, PPC, Direct Mail, Sales\",\"SEO, SEM, Ads, Marketing, PPC, Branding, Promotions\",,6/29/2012,active,bronze,Advertising & Marketing,Professional Services,,,,\n";
?>
