<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Latitude,Listing Longitude,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Oxford Gallery Inc,267 Oxford St,,United States,New York,Rochester,14607,(585) 271-5885,,,,,,Oxford Gallery Inc,,,267 Oxford St,,United States,USA,,,Rochester,NY,Rochester,,,,14607,,,(585) 271-5885,,Art Galleries and Artisan Shops,Art Galleries and Artisan Shops,Art Gallery||Art Dealers||Artisan Shops||Fine Art,,07/12/2012,active,bronze,\"Arts Entertainment and Nightlife->Art Galleries and Artisan Shops\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Renaissance Art Gallery,76 Saint Paul St,,United States,New York,Rochester,14604,(585) 423-8235,,,,,,Renaissance Art Gallery,,,76 Saint Paul St,,United States,USA,,,Rochester,NY,Rochester,,,,14604,,,(585) 423-8235,,Art Galleries and Artisan Shops,Art Galleries and Artisan Shops,Art Gallery||Art Dealers||Artisan Shops||Fine Art,,07/12/2012,active,bronze,\"Arts Entertainment and Nightlife->Art Galleries and Artisan Shops\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Gallery Store At Memorial Art,500 University Ave,,United States,New York,Rochester,14607,(585) 473-7228,,,,,,Gallery Store At Memorial Art,,,500 University Ave,,United States,USA,,,Rochester,NY,Rochester,,,,14607,,,(585) 473-7228,,Art Galleries and Artisan Shops,Art Galleries and Artisan Shops,Art Gallery||Art Dealers||Artisan Shops||Fine Art,,07/12/2012,active,bronze,\"Arts Entertainment and Nightlife->Art Galleries and Artisan Shops\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,International Art Acquisitions,3300 Monroe Ave # 105,,United States,New York,Rochester,14618,(585) 264-1440,,,,,,International Art Acquisitions,,,3300 Monroe Ave # 105,,United States,USA,,,Rochester,NY,Rochester,,,,14618,,,(585) 264-1440,,Art Galleries and Artisan Shops,Art Galleries and Artisan Shops,Art Gallery||Art Dealers||Artisan Shops||Fine Art,,07/12/2012,active,bronze,\"Arts Entertainment and Nightlife->Art Galleries and Artisan Shops\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,University of Rochester -  Museum Offices  Information/Memorial Art Gallery/magrochesteredu,500 University Ave,,United States,New York,Rochester,14607,(585) 276-8900,,,,,,University of Rochester -  Museum Offices  Information/Memorial Art Gallery/magrochesteredu,,,500 University Ave,,United States,USA,,,Rochester,NY,Rochester,,,,14607,,,(585) 276-8900,,Art Galleries and Artisan Shops,Art Galleries and Artisan Shops,Art Gallery||Art Dealers||Artisan Shops||Fine Art,,07/12/2012,active,bronze,\"Arts Entertainment and Nightlife->Art Galleries and Artisan Shops\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Art Rains,401 Parsells Ave,,United States,New York,Rochester,14609,(585) 288-2034,,,,,,Art Rains,,,401 Parsells Ave,,United States,USA,,,Rochester,NY,Rochester,,,,14609,,,(585) 288-2034,,Art Galleries and Artisan Shops,Art Galleries and Artisan Shops,Art Gallery||Art Dealers||Artisan Shops||Fine Art,,07/12/2012,active,bronze,\"Arts Entertainment and Nightlife->Art Galleries and Artisan Shops\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Gallery R,100 College Ave,,United States,New York,Rochester,14607,(585) 256-3312,,,,,,Gallery R,,,100 College Ave,,United States,USA,,,Rochester,NY,Rochester,,,,14607,,,(585) 256-3312,,Art Galleries and Artisan Shops,Art Galleries and Artisan Shops,Art Gallery||Art Dealers||Artisan Shops||Fine Art,,07/12/2012,active,bronze,\"Arts Entertainment and Nightlife->Art Galleries and Artisan Shops\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Young Audiences Inc,277 Goodman St N # H209,,United States,New York,Rochester,14607,(585) 530-2060,,,,,,Young Audiences Inc,,,277 Goodman St N # H209,,United States,USA,,,Rochester,NY,Rochester,,,,14607,,,(585) 530-2060,,Art Galleries and Artisan Shops,Art Galleries and Artisan Shops,Art Gallery||Art Dealers||Artisan Shops||Fine Art,,07/12/2012,active,bronze,\"Arts Entertainment and Nightlife->Art Galleries and Artisan Shops\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Jembetat African Art Gallery,645 Park Ave,,United States,New York,Rochester,14607,(585) 442-8960,,,,,,Jembetat African Art Gallery,,,645 Park Ave,,United States,USA,,,Rochester,NY,Rochester,,,,14607,,,(585) 442-8960,,Art Galleries and Artisan Shops,Art Galleries and Artisan Shops,Art Gallery||Art Dealers||Artisan Shops||Fine Art,,07/12/2012,active,bronze,\"Arts Entertainment and Nightlife->Art Galleries and Artisan Shops\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Art To Zen,4363 Lake Ave,,United States,New York,Rochester,14612,(585) 621-3515,,,,,,Art To Zen,,,4363 Lake Ave,,United States,USA,,,Rochester,NY,Rochester,,,,14612,,,(585) 621-3515,,Art Galleries and Artisan Shops,Art Galleries and Artisan Shops,Art Gallery||Art Dealers||Artisan Shops||Fine Art,,07/12/2012,active,bronze,\"Arts Entertainment and Nightlife->Art Galleries and Artisan Shops\",,,,,\n";
?>
