<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Latitude,Listing Longitude,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Camp Bow Wow,85 Mushroom Blvd,,United States,New York,Rochester,14623,(585) 613-9247,,,,,,Camp Bow Wow,,,85 Mushroom Blvd,,United States,USA,,,Rochester,NY,Rochester,,,,14623,,,(585) 613-9247,,Pet Boarding & Sitting Services,Pet Boarding & Sitting Services,Boarding||dog walking||pet feeding||pet sitting,,7/15/2012,active,bronze,\"Pet Services->Pet Boarding & Sitting Services\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Wooftown Doggy Daycare,,,United States,New York,Rochester,14624,(585) 298-3001,,,,,,Wooftown Doggy Daycare,,,,,United States,USA,,,Rochester,NY,Rochester,,,,14624,,,(585) 298-3001,,Pet Boarding & Sitting Services,Pet Boarding & Sitting Services,Boarding||dog walking||pet feeding||pet sitting,,7/15/2012,active,bronze,\"Pet Services->Pet Boarding & Sitting Services\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Flower City Pets,,,United States,New York,Rochester,14625,(585) 586-7020,,,,,,Flower City Pets,,,,,United States,USA,,,Rochester,NY,Rochester,,,,14625,,,(585) 586-7020,,Pet Boarding & Sitting Services,Pet Boarding & Sitting Services,Boarding||dog walking||pet feeding||pet sitting,,7/15/2012,active,bronze,\"Pet Services->Pet Boarding & Sitting Services\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Dogs At Play,75 Howell St,,United States,New York,Rochester,14607,(585) 325-3647,,,,,,Dogs At Play,,,75 Howell St,,United States,USA,,,Rochester,NY,Rochester,,,,14607,,,(585) 325-3647,,Pet Boarding & Sitting Services,Pet Boarding & Sitting Services,Boarding||dog walking||pet feeding||pet sitting,,7/15/2012,active,bronze,\"Pet Services->Pet Boarding & Sitting Services\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Fluffypaw's Pet Luv,2124 Maiden Ln,,United States,New York,Rochester,14626,(585) 366-4437,,,,,,Fluffypaw's Pet Luv,,,2124 Maiden Ln,,United States,USA,,,Rochester,NY,Rochester,,,,14626,,,(585) 366-4437,,Pet Boarding & Sitting Services,Pet Boarding & Sitting Services,Boarding||dog walking||pet feeding||pet sitting,,7/15/2012,active,bronze,\"Pet Services->Pet Boarding & Sitting Services\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Tlc Pet Sitting Svc Inc,108 Images Way,,United States,New York,Rochester,14626,(585) 663-1540,,,,,,Tlc Pet Sitting Svc Inc,,,108 Images Way,,United States,USA,,,Rochester,NY,Rochester,,,,14626,,,(585) 663-1540,,Pet Boarding & Sitting Services,Pet Boarding & Sitting Services,Boarding||dog walking||pet feeding||pet sitting,,7/15/2012,active,bronze,\"Pet Services->Pet Boarding & Sitting Services\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Fluffypaw's Pet Love,,,United States,New York,Rochester,14626,(585) 366-4437,,,,,,Fluffypaw's Pet Love,,,,,United States,USA,,,Rochester,NY,Rochester,,,,14626,,,(585) 366-4437,,Pet Boarding & Sitting Services,Pet Boarding & Sitting Services,Boarding||dog walking||pet feeding||pet sitting,,7/15/2012,active,bronze,\"Pet Services->Pet Boarding & Sitting Services\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Pet Express of Monroe County,,,United States,New York,Rochester,14602,(585) 242-0526,,,,,,Pet Express of Monroe County,,,,,United States,USA,,,Rochester,NY,Rochester,,,,14602,,,(585) 242-0526,,Pet Boarding & Sitting Services,Pet Boarding & Sitting Services,Boarding||dog walking||pet feeding||pet sitting,,7/15/2012,active,bronze,\"Pet Services->Pet Boarding & Sitting Services\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,A Dog's Dream,3300 Monroe Ave,,United States,New York,Rochester,14618,(585) 267-7865,,,,,,A Dog's Dream,,,3300 Monroe Ave,,United States,USA,,,Rochester,NY,Rochester,,,,14618,,,(585) 267-7865,,Pet Boarding & Sitting Services,Pet Boarding & Sitting Services,Boarding||dog walking||pet feeding||pet sitting,,7/15/2012,active,bronze,\"Pet Services->Pet Boarding & Sitting Services\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Creature Comfort Pet Sitters,1374 Allen Rd,,United States,New York,Penfield,14526,(585) 872-9190,,,,,,Creature Comfort Pet Sitters,,,1374 Allen Rd,,United States,USA,,,Rochester,NY,Penfield,,,,14526,,,(585) 872-9190,,Pet Boarding & Sitting Services,Pet Boarding & Sitting Services,Boarding||dog walking||pet feeding||pet sitting,,7/15/2012,active,bronze,\"Pet Services->Pet Boarding & Sitting Services\",,,,,\n";
?>
