<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Latitude,Listing Longitude,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,1 800 LIMO NOW,,,United States,New York,,,(888) 395-1365,,,,,,1 800 LIMO NOW,,,,,United States,USA,,,New York,,,,,,,,,(888) 395-1365,,Taxi & Limousine Services,Taxi & Limousine Services,Taxi||Limousine||Bus||Shuttle||Transportation||Taxi Cab,,7/5/2012,active,bronze,Taxi & Limousine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,PT Group,,,United States,New York,,,(877) 851-9116,,,,,,PT Group,,,,,United States,USA,,,New York,,,,,,,,,(877) 851-9116,,Taxi & Limousine Services,Taxi & Limousine Services,Taxi||Limousine||Bus||Shuttle||Transportation||Taxi Cab,,7/5/2012,active,bronze,Taxi & Limousine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Golden Knight Limousine,2120 Long Pond Rd,,United States,New York,Rochester,14606,(585) 568-8939,,,,,,Golden Knight Limousine,,,2120 Long Pond Rd,,United States,USA,,,New York,NY,Rochester,,,,14606,,,(585) 568-8939,,Taxi & Limousine Services,Taxi & Limousine Services,Taxi||Limousine||Bus||Shuttle||Transportation||Taxi Cab,,7/5/2012,active,bronze,Taxi & Limousine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Excel Limousine Serv,1124-1/2 E Ridge Rd,,United States,New York,Rochester,14621,(585) 544-4060,,,,,,Excel Limousine Serv,,,1124-1/2 E Ridge Rd,,United States,USA,,,New York,NY,Rochester,,,,14621,,,(585) 544-4060,,Taxi & Limousine Services,Taxi & Limousine Services,Taxi||Limousine||Bus||Shuttle||Transportation||Taxi Cab,,7/5/2012,active,bronze,Taxi & Limousine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,L & E Limousine Svc,1275 Mount Read Blvd,,United States,New York,Rochester,14606,(585) 482-8961,,,,,,L & E Limousine Svc,,,1275 Mount Read Blvd,,United States,USA,,,New York,NY,Rochester,,,,14606,,,(585) 482-8961,,Taxi & Limousine Services,Taxi & Limousine Services,Taxi||Limousine||Bus||Shuttle||Transportation||Taxi Cab,,7/5/2012,active,bronze,Taxi & Limousine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,S & S Limousines,7160 W Main Rd,,United States,New York,Le Roy,14482,(585) 768-6868,,,,,,S & S Limousines,,,7160 W Main Rd,,United States,USA,,,New York,NY,Le Roy,,,,14482,,,(585) 768-6868,,Taxi & Limousine Services,Taxi & Limousine Services,Taxi||Limousine||Bus||Shuttle||Transportation||Taxi Cab,,7/5/2012,active,bronze,Taxi & Limousine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Mancuso Limousines of WNY,,,United States,New York,,,(888) 533-4099,,,,,,Mancuso Limousines of WNY,,,,,United States,USA,,,New York,,,,,,,,,(888) 533-4099,,Taxi & Limousine Services,Taxi & Limousine Services,Taxi||Limousine||Bus||Shuttle||Transportation||Taxi Cab,,7/5/2012,active,bronze,Taxi & Limousine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Rochester Shuttle Express,,,United States,New York,Rochester,14615,(585) 663-3760,,,,,,Rochester Shuttle Express,,,,,United States,USA,,,New York,NY,Rochester,,,,14615,,,(585) 663-3760,,Taxi & Limousine Services,Taxi & Limousine Services,Taxi||Limousine||Bus||Shuttle||Transportation||Taxi Cab,,7/5/2012,active,bronze,Taxi & Limousine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Esteem Limousine & Corporate Travel Of Western NY,28 Hidden Spring Cir,,United States,New York,Rochester,14616,(585) 225-7333,,,,,,Esteem Limousine & Corporate Travel Of Western NY,,,28 Hidden Spring Cir,,United States,USA,,,New York,NY,Rochester,,,,14616,,,(585) 225-7333,,Taxi & Limousine Services,Taxi & Limousine Services,Taxi||Limousine||Bus||Shuttle||Transportation||Taxi Cab,,7/5/2012,active,bronze,Taxi & Limousine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Addamo/Imperial Limousines,233 Laurelton Rd,,United States,New York,Rochester,14609,(585) 288-2277,,,,,,Addamo/Imperial Limousines,,,233 Laurelton Rd,,United States,USA,,,New York,NY,Rochester,,,,14609,,,(585) 288-2277,,Taxi & Limousine Services,Taxi & Limousine Services,Taxi||Limousine||Bus||Shuttle||Transportation||Taxi Cab,,7/5/2012,active,bronze,Taxi & Limousine Services,,,,,\n";
?>
