<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Latitude,Listing Longitude,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,American Standard Heating & Air Conditioning,,,United States,New York,,,,,,,,,American Standard Heating & Air Conditioning,,,,,United States,USA,,,New York,,,,,,,,,,,Air Conditioning Experts,Air Conditioning Experts,HVAC||Home Air Conditioner||Home Heating,,7/5/2012,active,bronze,Air Conditioning Experts,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Betlem John Heating And Cooling Inc,898 Clinton Ave S,,United States,New York,Rochester,14620,(585) 271-8888,,,,,,Betlem John Heating And Cooling Inc,,,898 Clinton Ave S,,United States,USA,,,New York,NY,Rochester,,,,14620,,,(585) 271-8888,,Air Conditioning Experts,Air Conditioning Experts,HVAC||Home Air Conditioner||Home Heating,,7/5/2012,active,bronze,Air Conditioning Experts,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Isaac Heating & Air Conditioning,180 Charlotte St,,United States,New York,Rochester,14607,(585) 546-1400,,,,,,Isaac Heating & Air Conditioning,,,180 Charlotte St,,United States,USA,,,New York,NY,Rochester,,,,14607,,,(585) 546-1400,,Air Conditioning Experts,Air Conditioning Experts,HVAC||Home Air Conditioner||Home Heating,,7/5/2012,active,bronze,Air Conditioning Experts,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Airquip Heating & Air Conditioning,830 Linden Ave,,United States,New York,Rochester,14625,(585) 641-3080,,,,,,Airquip Heating & Air Conditioning,,,830 Linden Ave,,United States,USA,,,New York,NY,Rochester,,,,14625,,,(585) 641-3080,,Air Conditioning Experts,Air Conditioning Experts,HVAC||Home Air Conditioner||Home Heating,,7/5/2012,active,bronze,Air Conditioning Experts,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Air Dispatch,30 Industrial Park Cir,,United States,New York,Rochester,14624,(585) 436-5738,,,,,,Air Dispatch,,,30 Industrial Park Cir,,United States,USA,,,New York,NY,Rochester,,,,14624,,,(585) 436-5738,,Air Conditioning Experts,Air Conditioning Experts,HVAC||Home Air Conditioner||Home Heating,,7/5/2012,active,bronze,Air Conditioning Experts,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Crossfield Heating & Air Conditioning Inc,44 Donovan St,,United States,New York,Webster,14580,,,,,,,Crossfield Heating & Air Conditioning Inc,,,44 Donovan St,,United States,USA,,,New York,NY,Webster,,,,14580,,,,,Air Conditioning Experts,Air Conditioning Experts,HVAC||Home Air Conditioner||Home Heating,,7/5/2012,active,bronze,Air Conditioning Experts,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Taylor Heating Inc.,325 Mount Read Blvd,,United States,New York,Rochester,14611,(585) 328-9260,,,,,,Taylor Heating Inc.,,,325 Mount Read Blvd,,United States,USA,,,New York,NY,Rochester,,,,14611,,,(585) 328-9260,,Air Conditioning Experts,Air Conditioning Experts,HVAC||Home Air Conditioner||Home Heating,,7/5/2012,active,bronze,Air Conditioning Experts,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Northern Comfort Heating & Cooling Inc,6080 Pittsford Palmyra Rd,,United States,New York,Fairport,14450,(585) 223-4480,,,,,,Northern Comfort Heating & Cooling Inc,,,6080 Pittsford Palmyra Rd,,United States,USA,,,New York,NY,Fairport,,,,14450,,,(585) 223-4480,,Air Conditioning Experts,Air Conditioning Experts,HVAC||Home Air Conditioner||Home Heating,,7/5/2012,active,bronze,Air Conditioning Experts,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Sears Home Improvement Products,150 Mile Crossing Blvd,,United States,New York,Rochester,14624,(888) 576-3502,,,,,,Sears Home Improvement Products,,,150 Mile Crossing Blvd,,United States,USA,,,New York,NY,Rochester,,,,14624,,,(888) 576-3502,,Air Conditioning Experts,Air Conditioning Experts,HVAC||Home Air Conditioner||Home Heating,,7/5/2012,active,bronze,Air Conditioning Experts,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Hawn Heating and Air,277 N Winton Rd,,United States,New York,Rochester,14610,(888) 492-0168,,,,,,Hawn Heating and Air,,,277 N Winton Rd,,United States,USA,,,New York,NY,Rochester,,,,14610,,,(888) 492-0168,,Air Conditioning Experts,Air Conditioning Experts,HVAC||Home Air Conditioner||Home Heating,,7/5/2012,active,bronze,Air Conditioning Experts,,,,,\n";
?>
