<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Latitude,Listing Longitude,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo "russ@dealcloudusa.com,M@rket1ng,,,A & J Tax Inc,1225 Long Pond Rd,,United States,New York,Rochester,14626,(585) 227-4626,,russ@dealcloudusa.com,,,,A & J Tax Inc,,,1225 Long Pond Rd,,United States,USA,,,New York,NY,Rochester,,,,14626,,,(585) 227-4626,,Accounting and CPA Services,\"Accounting and CPA Services - Payroll, Tax, Corporate, Personal\",CPA||Rochester||Accountant|Payroll||Tax ||Local||NY,,6/29/2013,Active,bronze,,,,,,\n";
	echo "russ@dealcloudusa.com,M@rket1ng,,,ABC Liquor License Applctn,726 Titus Ave,,United States,New York,Rochester,14617,(585) 342-4868,,russ@dealcloudusa.com,,,,ABC Liquor License Applctn,,,726 Titus Ave,,United States,USA,,,New York,NY,Rochester,,,,14617,,,(585) 342-4868,,Accounting and CPA Services,\"Accounting and CPA Services - Payroll, Tax, Corporate, Personal\",CPA||Rochester||Accountant|Payroll||Tax ||Local||NY,,6/29/2013,Active,bronze,,,,,,\n";
	echo "russ@dealcloudusa.com,M@rket1ng,,,\"Accountants in Rochester New York, LLC\",214 Berkeley St - Suite 10 - ACCT,,United States,New York,Rochester,14607,(585) 466-4059,,russ@dealcloudusa.com,,,,\"Accountants in Rochester New York, LLC\",,,214 Berkeley St - Suite 10 - ACCT,,United States,USA,,,New York,NY,Rochester,,,,14607,,,(585) 466-4059,,Accounting and CPA Services,\"Accounting and CPA Services - Payroll, Tax, Corporate, Personal\",CPA||Rochester||Accountant|Payroll||Tax ||Local||NY,,6/29/2013,Active,bronze,,,,,,\n";
	echo "russ@dealcloudusa.com,M@rket1ng,,,Accountemps,640 Clinton Sq,,United States,New York,Rochester,14604,(585) 232-6055,,russ@dealcloudusa.com,,,,Accountemps,,,640 Clinton Sq,,United States,USA,,,New York,NY,Rochester,,,,14604,,,(585) 232-6055,,Accounting and CPA Services,\"Accounting and CPA Services - Payroll, Tax, Corporate, Personal\",CPA||Rochester||Accountant|Payroll||Tax ||Local||NY,,6/29/2013,Active,bronze,,,,,,\n";
	echo "russ@dealcloudusa.com,M@rket1ng,,,Accounting For Sm Businesses,3300 Monroe Ave # 314,,United States,New York,Rochester,14618,(585) 249-0358,,russ@dealcloudusa.com,,,,Accounting For Sm Businesses,,,3300 Monroe Ave # 314,,United States,USA,,,New York,NY,Rochester,,,,14618,,,(585) 249-0358,,Accounting and CPA Services,\"Accounting and CPA Services - Payroll, Tax, Corporate, Personal\",CPA||Rochester||Accountant|Payroll||Tax ||Local||NY,,6/29/2013,Active,bronze,,,,,,\n";
	echo "russ@dealcloudusa.com,M@rket1ng,,,Accounting Services Plus,329 Sunset St,,United States,New York,Rochester,14606,(585) 458-2580,,russ@dealcloudusa.com,,,,Accounting Services Plus,,,329 Sunset St,,United States,USA,,,New York,NY,Rochester,,,,14606,,,(585) 458-2580,,Accounting and CPA Services,\"Accounting and CPA Services - Payroll, Tax, Corporate, Personal\",CPA||Rochester||Accountant|Payroll||Tax ||Local||NY,,6/29/2013,Active,bronze,,,,,,\n";
	echo "russ@dealcloudusa.com,M@rket1ng,,,Accu-Books,891 Dewitt Rd,,United States,New York,Webster,14580,(585) 671-0490,,russ@dealcloudusa.com,,,,Accu-Books,,,891 Dewitt Rd,,United States,USA,,,New York,NY,Webster,,,,14580,,,(585) 671-0490,,Accounting and CPA Services,\"Accounting and CPA Services - Payroll, Tax, Corporate, Personal\",CPA||Rochester||Accountant|Payroll||Tax ||Local||NY,,6/29/2013,Active,bronze,,,,,,\n";
	echo "russ@dealcloudusa.com,M@rket1ng,,,\"Accu-Tax, Ltd.\",27 Briarwood Dr,,United States,New York,Rochester,14617,(877) 432-9862,,russ@dealcloudusa.com,,,,\"Accu-Tax, Ltd.\",,,27 Briarwood Dr,,United States,USA,,,New York,NY,Rochester,,,,14617,,,(877) 432-9862,,Accounting and CPA Services,\"Accounting and CPA Services - Payroll, Tax, Corporate, Personal\",CPA||Rochester||Accountant|Payroll||Tax ||Local||NY,,6/29/2013,Active,bronze,,,,,,\n";
	echo "russ@dealcloudusa.com,M@rket1ng,,,Adams Edw F CPA,100 Chestnut St,,United States,New York,Rochester,14604,(585) 442-7980,,russ@dealcloudusa.com,,,,Adams Edw F CPA,,,100 Chestnut St,,United States,USA,,,New York,NY,Rochester,,,,14604,,,(585) 442-7980,,Accounting and CPA Services,\"Accounting and CPA Services - Payroll, Tax, Corporate, Personal\",CPA||Rochester||Accountant|Payroll||Tax ||Local||NY,,6/29/2013,Active,bronze,,,,,,\n";
	echo "russ@dealcloudusa.com,M@rket1ng,,,Adams Paul CPA,1870 Winton Rd S,,United States,New York,Rochester,14618,(585) 295-2400,,russ@dealcloudusa.com,,,,Adams Paul CPA,,,1870 Winton Rd S,,United States,USA,,,New York,NY,Rochester,,,,14618,,,(585) 295-2400,,Accounting and CPA Services,\"Accounting and CPA Services - Payroll, Tax, Corporate, Personal\",CPA||Rochester||Accountant|Payroll||Tax ||Local||NY,,6/29/2013,Active,bronze,,,,,,\n";
?>
