<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Latitude,Listing Longitude,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo ",,,,Firestone Complete Auto Care,3931 Maple Rd,,United States,New York,Buffalo,14226,,,,,,,Firestone Complete Auto Care,,,3931 Maple Rd,,United States,USA,,,New York,NY,Buffalo,,,,14226,,,,,Air Conditioning Service,,,,10/5/2013,active,bronze,Air Conditioning Service->Automobile Air Conditioning Services,,,,,\n";
	echo ",,,,AAMCO Transmissions,3454 Sheridan Dr,,United States,New York,Buffalo,14226,(716) 837-6542,,,,,,AAMCO Transmissions,,,3454 Sheridan Dr,,United States,USA,,,New York,NY,Buffalo,,,,14226,,,(716) 837-6542,,Air Conditioning Service,,,,10/5/2013,active,bronze,Air Conditioning Service->Automobile Air Conditioning Services,,,,,\n";
	echo ",,,,Auto Elec Co,1580 Seneca St,,United States,New York,Buffalo,14210,(716) 823-8200,,,,,,Auto Elec Co,,,1580 Seneca St,,United States,USA,,,New York,NY,Buffalo,,,,14210,,,(716) 823-8200,,Air Conditioning Service,,,,10/5/2013,active,bronze,Air Conditioning Service->Automobile Air Conditioning Services,Air Conditioning Service->Residential Air Conditioning Services,,,,\n";
	echo ",,,,Don's Auto,1440 Electric Ave,,United States,New York,Buffalo,14218,(716) 825-0676,,,,,,Don's Auto,,,1440 Electric Ave,,United States,USA,,,New York,NY,Buffalo,,,,14218,,,(716) 825-0676,,Air Conditioning Service,,,,10/5/2013,active,bronze,Air Conditioning Service->Automobile Air Conditioning Services,,,,,\n";
	echo ",,,,Midas Auto Service Experts,1171 Niagara Falls Blvd,,United States,New York,Buffalo,14226,(716) 837-4100,,,,,,Midas Auto Service Experts,,,1171 Niagara Falls Blvd,,United States,USA,,,New York,NY,Buffalo,,,,14226,,,(716) 837-4100,,Air Conditioning Service,,,,10/5/2013,active,bronze,Air Conditioning Service->Automobile Air Conditioning Services,,,,,\n";
	echo ",,,,Meineke Car Care Center,3955 Harlem Rd,,United States,New York,Buffalo,14226,(716) 803-8556,,,,,,Meineke Car Care Center,,,3955 Harlem Rd,,United States,USA,,,New York,NY,Buffalo,,,,14226,,,(716) 803-8556,,Air Conditioning Service,,,,10/5/2013,active,bronze,Air Conditioning Service->Automobile Air Conditioning Services,,,,,\n";
	echo ",,,,Midas Auto Service Experts,315 Niagara St,,United States,New York,Buffalo,14201,(716) 852-1121,,,,,,Midas Auto Service Experts,,,315 Niagara St,,United States,USA,,,New York,NY,Buffalo,,,,14201,,,(716) 852-1121,,Air Conditioning Service,,,,10/5/2013,active,bronze,Air Conditioning Service->Automobile Air Conditioning Services,,,,,\n";
	echo ",,,,Daved's Auto Center,795 Bailey Ave,,United States,New York,Buffalo,14206,(716) 823-0700,,,,,,Daved's Auto Center,,,795 Bailey Ave,,United States,USA,,,New York,NY,Buffalo,,,,14206,,,(716) 823-0700,,Air Conditioning Service,,,,10/5/2013,active,bronze,Air Conditioning Service->Automobile Air Conditioning Services,Air Conditioning Service->Residential Air Conditioning Services,,,,\n";
	echo ",,,,Midas Auto Service Experts,3781 Delaware Ave,,United States,New York,Buffalo,14217,(716) 876-5244,,,,,,Midas Auto Service Experts,,,3781 Delaware Ave,,United States,USA,,,New York,NY,Buffalo,,,,14217,,,(716) 876-5244,,Air Conditioning Service,,,,10/5/2013,active,bronze,Air Conditioning Service->Automobile Air Conditioning Services,,,,,\n";
	echo ",,,,Thru-Way Auto Air & Accessory,30 Dyke Rd,,United States,New York,Buffalo,14224,(716) 675-9800,,,,,,Thru-Way Auto Air & Accessory,,,30 Dyke Rd,,United States,USA,,,New York,NY,Buffalo,,,,14224,,,(716) 675-9800,,Air Conditioning Service,,,,10/5/2013,active,bronze,Air Conditioning Service->Automobile Air Conditioning Services,Air Conditioning Service->Residential Air Conditioning Services,,,,\n";
?>
