<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Latitude,Listing Longitude,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,John D'aurizio Law Offices,1780 E Ridge Rd Ste 7,,United States,New York,Rochester,14622,(585) 678-5802,,,,,,John D'aurizio Law Offices,,,1780 E Ridge Rd Ste 7,,United States,USA,,,New York,NY,Rochester,,,,14622,,,(585) 678-5802,,Corporate Business Attorneys Lawyers,Corporate Business Attorneys Lawyers,Corporate||Attorney||Lawyer||Law||Law Firm,,7/11/2012,active,bronze,Attorneys Lawyers->Corporate Business Attorneys Lawyers\"\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Lacy Katzen LLP,130 E Main St,,United States,New York,Rochester,14604,(585) 454-5650,,,,,,Lacy Katzen LLP,,,130 E Main St,,United States,USA,,,New York,NY,Rochester,,,,14604,,,(585) 454-5650,,Corporate Business Attorneys Lawyers,Corporate Business Attorneys Lawyers,Corporate||Attorney||Lawyer||Law||Law Firm,,7/11/2012,active,bronze,Attorneys Lawyers->Corporate Business Attorneys Lawyers\"\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Boylan Code LLP,145 Culver Rd Ste 100,,United States,New York,Rochester,14620,(585) 232-5300,,,,,,Boylan Code LLP,,,145 Culver Rd Ste 100,,United States,USA,,,New York,NY,Rochester,,,,14620,,,(585) 232-5300,,Corporate Business Attorneys Lawyers,Corporate Business Attorneys Lawyers,Corporate||Attorney||Lawyer||Law||Law Firm,,7/11/2012,active,bronze,Attorneys Lawyers->Corporate Business Attorneys Lawyers\"\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,\"Steinbrenner Law Offices, LLC\",104 Troup St,,United States,New York,Rochester,14608,(800) 862-3149,,,,,,\"Steinbrenner Law Offices, LLC\",,,104 Troup St,,United States,USA,,,New York,NY,Rochester,,,,14608,,,(800) 862-3149,,Corporate Business Attorneys Lawyers,Corporate Business Attorneys Lawyers,Corporate||Attorney||Lawyer||Law||Law Firm,,7/11/2012,active,bronze,Attorneys Lawyers->Corporate Business Attorneys Lawyers\"\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Hirt Jared P Atty,95 Allens Creek Rd Ste 300,,United States,New York,Rochester,14618,(585) 241-5999,,,,,,Hirt Jared P Atty,,,95 Allens Creek Rd Ste 300,,United States,USA,,,New York,NY,Rochester,,,,14618,,,(585) 241-5999,,Corporate Business Attorneys Lawyers,Corporate Business Attorneys Lawyers,Corporate||Attorney||Lawyer||Law||Law Firm,,7/11/2012,active,bronze,Attorneys Lawyers->Corporate Business Attorneys Lawyers\"\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Adair Law Firm LLP,290 Linden Oaks Suite 220,,United States,New York,Rochester,14625,(585) 419-9000,,,,,,Adair Law Firm LLP,,,290 Linden Oaks Suite 220,,United States,USA,,,New York,NY,Rochester,,,,14625,,,(585) 419-9000,,Corporate Business Attorneys Lawyers,Corporate Business Attorneys Lawyers,Corporate||Attorney||Lawyer||Law||Law Firm,,7/11/2012,active,bronze,Attorneys Lawyers->Corporate Business Attorneys Lawyers\"\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Spiegel & Utrera,,,United States,New York,Rochester,14618,(585) 442-9640,,,,,,Spiegel & Utrera,,,,,United States,USA,,,New York,NY,Rochester,,,,14618,,,(585) 442-9640,,Corporate Business Attorneys Lawyers,Corporate Business Attorneys Lawyers,Corporate||Attorney||Lawyer||Law||Law Firm,,7/11/2012,active,bronze,Attorneys Lawyers->Corporate Business Attorneys Lawyers\"\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Vincent J Criscuolo & Assoc,130 W Main St # 220,,United States,New York,Rochester,14614,(585) 232-3240,,,,,,Vincent J Criscuolo & Assoc,,,130 W Main St # 220,,United States,USA,,,New York,NY,Rochester,,,,14614,,,(585) 232-3240,,Corporate Business Attorneys Lawyers,Corporate Business Attorneys Lawyers,Corporate||Attorney||Lawyer||Law||Law Firm,,7/11/2012,active,bronze,Attorneys Lawyers->Corporate Business Attorneys Lawyers\"\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Burkhart WM E Jr,450 Reynolds Arcade Bldg,,United States,New York,Rochester,14614,(585) 325-1750,,,,,,Burkhart WM E Jr,,,450 Reynolds Arcade Bldg,,United States,USA,,,New York,NY,Rochester,,,,14614,,,(585) 325-1750,,Corporate Business Attorneys Lawyers,Corporate Business Attorneys Lawyers,Corporate||Attorney||Lawyer||Law||Law Firm,,7/11/2012,active,bronze,Attorneys Lawyers->Corporate Business Attorneys Lawyers\"\",,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Wallen John C,36 W Main St # 785,,United States,New York,Rochester,14614,(585) 454-7660,,,,,,Wallen John C,,,36 W Main St # 785,,United States,USA,,,New York,NY,Rochester,,,,14614,,,(585) 454-7660,,Corporate Business Attorneys Lawyers,Corporate Business Attorneys Lawyers,Corporate||Attorney||Lawyer||Law||Law Firm,,7/11/2012,active,bronze,Attorneys Lawyers->Corporate Business Attorneys Lawyers\"\",,,,,\n";
?>
