<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Latitude,Listing Longitude,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,TAXI ROCHESTER NY,1115 East  Main St 75,,United States,New York,rochester,14609,(585) 647-9999,,,,,,TAXI ROCHESTER NY,,,1115 East  Main St 75,,United States,USA,,,New York,NY,rochester,,,,14609,,,(585) 647-9999,,Taxi Services,Taxi Services,Taxi||Limousine||Shuttle||Taxi Cab||Transportation,,7/5/2012,active,bronze,Taxi & Limosine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Five Star Taxi,,,United States,New York,Rochester,14606,(585) 489-6033,,,,,,Five Star Taxi,,,,,United States,USA,,,New York,NY,Rochester,,,,14606,,,(585) 489-6033,,Taxi Services,Taxi Services,Taxi||Limousine||Shuttle||Taxi Cab||Transportation,,7/5/2012,active,bronze,Taxi & Limosine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,A 1 Elite Taxi Service,10 Karen Dr,,United States,New York,Rochester,14606,(585) 506-5118,,,,,,A 1 Elite Taxi Service,,,10 Karen Dr,,United States,USA,,,New York,NY,Rochester,,,,14606,,,(585) 506-5118,,Taxi Services,Taxi Services,Taxi||Limousine||Shuttle||Taxi Cab||Transportation,,7/5/2012,active,bronze,Taxi & Limosine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Yellow Cab Rochester,,,United States,New York,Rochester,14618,(585) 978-9099,,,,,,Yellow Cab Rochester,,,,,United States,USA,,,New York,NY,Rochester,,,,14618,,,(585) 978-9099,,Taxi Services,Taxi Services,Taxi||Limousine||Shuttle||Taxi Cab||Transportation,,7/5/2012,active,bronze,Taxi & Limosine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Hummingbird Taxi Inc,1597 W Ridge Rd Ste 101-D,,United States,New York,Rochester,14615,(585) 633-8573,,,,,,Hummingbird Taxi Inc,,,1597 W Ridge Rd Ste 101-D,,United States,USA,,,New York,NY,Rochester,,,,14615,,,(585) 633-8573,,Taxi Services,Taxi Services,Taxi||Limousine||Shuttle||Taxi Cab||Transportation,,7/5/2012,active,bronze,Taxi & Limosine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Checker Cab,803 West Ave,,United States,New York,Rochester,14611,(585) 325-2460,,,,,,Checker Cab,,,803 West Ave,,United States,USA,,,New York,NY,Rochester,,,,14611,,,(585) 325-2460,,Taxi Services,Taxi Services,Taxi||Limousine||Shuttle||Taxi Cab||Transportation,,7/5/2012,active,bronze,Taxi & Limosine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,GOLDEN ROCHESTER TAXI,1000 Monroe Ave,,United States,New York,Rochester,14620,(585) 957-2470,,,,,,GOLDEN ROCHESTER TAXI,,,1000 Monroe Ave,,United States,USA,,,New York,NY,Rochester,,,,14620,,,(585) 957-2470,,Taxi Services,Taxi Services,Taxi||Limousine||Shuttle||Taxi Cab||Transportation,,7/5/2012,active,bronze,Taxi & Limosine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Campus Taxi,6970 Chili Riga Center Rd,,United States,New York,Churchville,14428,(585) 703-4222,,,,,,Campus Taxi,,,6970 Chili Riga Center Rd,,United States,USA,,,New York,NY,Churchville,,,,14428,,,(585) 703-4222,,Taxi Services,Taxi Services,Taxi||Limousine||Shuttle||Taxi Cab||Transportation,,7/5/2012,active,bronze,Taxi & Limosine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,United B. Taxi Service,86 University Ave,,United States,New York,Rochester,14605,(585) 454-4444,,,,,,United B. Taxi Service,,,86 University Ave,,United States,USA,,,New York,NY,Rochester,,,,14605,,,(585) 454-4444,,Taxi Services,Taxi Services,Taxi||Limousine||Shuttle||Taxi Cab||Transportation,,7/5/2012,active,bronze,Taxi & Limosine Services,,,,,\n";
	echo "rochesterny@dealcloudusa.com,M@rket1ng,,,Par Cab,181 Traver Cir,,United States,New York,Rochester,14609,(585) 503-6400,,,,,,Par Cab,,,181 Traver Cir,,United States,USA,,,New York,NY,Rochester,,,,14609,,,(585) 503-6400,,Taxi Services,Taxi Services,Taxi||Limousine||Shuttle||Taxi Cab||Transportation,,7/5/2012,active,bronze,Taxi & Limosine Services,,,,,\n";
?>
